version: '3'
services:
  mongodb:
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  authservice:
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  userservice:
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  gatewayservice:
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
  
  webapp:
    ports:
      - "3000:3000"

networks:
  mynetwork:
    driver: bridge

