version: '3'
services:
  mongodb:
    container_name: mongodb-${teamname:-defaultASW}
    image: mongo
    volumes:
      - mongodb_data:/data/db

  authservice:
    container_name: authservice-${teamname:-defaultASW}
    image: ghcr.io/pglez82/asw2324_0/authservice:latest
    depends_on:
      - mongodb

  userservice:
    container_name: userservice-${teamname:-defaultASW}
    image: ghcr.io/pglez82/asw2324_0/userservice:latest
    depends_on:
      - mongodb

  gatewayservice:
    container_name: gatewayservice-${teamname:-defaultASW}
    image: ghcr.io/pglez82/asw2324_0/gatewayservice:latest
    depends_on:
      - mongodb
      - userservice
      - authservice

  webapp:
    container_name: webapp-${teamname:-defaultASW}
    image: ghcr.io/pglez82/asw2324_0/webapp:latest
    depends_on:
      - gatewayservice 

volumes:
  mongodb_data:
