version: '3'
services:
  mongodb:
    container_name: mongodb-${teamname:-defaultASW}
    image: mongo
    volumes:
      - mongodb_data:/data/db

  authservice:
    container_name: authservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_0/authservice:latest
    build: ./users/authservice
    depends_on:
      - mongodb

  userservice:
    container_name: userservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_0/userservice:latest
    build: ./users/userservice
    depends_on:
      - mongodb

  gatewayservice:
    container_name: gatewayservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_0/gatewayservice:latest
    build: ./gatewayservice
    depends_on:
      - mongodb
      - userservice
      - authservice

  webapp:
    container_name: webapp-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_0/webapp:latest
    build: ./webapp
    depends_on:
      - gatewayservice 

volumes:
  mongodb_data:
