openapi: 3.0.0
info:
  title: User Stats API
  description: UserStats OpenAPI specification.
  version: 0.3.1
servers:
  - url: http://localhost:8003
    description: Development server
  - url: http://userstatsservice:8003
    description: Production server
paths:
  /history/game:
    post:
      summary: Stores the actual game in the database.
      operationId: historyGame
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Game Id.
                  example: sqeweg12er56yg46u89k
                username:
                  type: string
                  description: The name if the user.
                  example: student
                points:
                  type: integer
                  description: The number of points that the user score.
                  example: 1000
                questions:
                  type: array
                  items:
                    type: object
                    properties:
                      question:
                        type: string
                        description: The question that is going to be done.
                        example: ¿Cuál es la capital de España?
                      correctAnswer:
                        type: string
                        description: The correct answer for the question.
                        example: Madrid
                      answers:
                        type: array
                        items:
                          type: string
                          description: List with the possible answers.
                          example: Madrid, Paris, Roma o Londres (en dif items)
                avgtime:
                  type: integer
                  description: The average time taken to answer questions in seconds.
                  example: 23
      responses:
        '200':
          description: Game created and returned successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Game Id.
                    example: sqeweg12er56yg46u89k
                  username:
                    type: string
                    description: The name if the user.
                    example: student
                  points:
                    type: integer
                    description: The number of points that the user scored.
                    example: 1000
                  avgtime:
                    type: integer
                    description: The average time taken to answer questions in seconds.
                    example: 23
                  questions:
                    type: array
                    items:
                      type: object
                      properties:
                        question:
                          type: string
                          description: The question that was done.
                          example: ¿Cuál es la capital de España?
                        correctAnswer:
                          type: string
                          description: The correct answer for the question.
                          example: Madrid
                        answers:
                          type: array
                          items:
                            type: string
                            description: List with the possible answers.
                            example: Madrid, Paris, Roma o Londres (en diferentes items)
                  createdAt:
                    type: string
                    format: date-time
                    description: Creation date and time of the game.
                    example: '2024-03-17T20:47:23.935Z'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
                    example: Bad Request
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
                    example: Internal Server Error

  /history/games/{username}:
    get:
      summary: Access to the history of games of the user.
      operationId: historyGames
      parameters:
        - name: username
          in: path
          required: true
          description: Username of the user.
          schema:
            type: string
            example: student
      responses:
        '200':
          description: Information of games returned successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Game Id.
                      example: sqeweg12er56yg46u89k
                    username:
                      type: string
                      description: Username of the user.
                      example: student
                    points:
                      type: integer
                      description: The number of points that the user scored.
                      example: 1000
                    avgtime:
                      type: integer
                      description: The average time taken to answer questions in seconds.
                      example: 23
                    questions:
                      type: array
                      items:
                        type: object
                        properties:
                          question:
                            type: string
                            description: The question that was done.
                            example: ¿Cuál es la capital de España?
                          correctAnswer:
                            type: string
                            description: The correct answer for the question.
                            example: Madrid
                          answers:
                            type: array
                            items:
                              type: string
                              description: List with the possible answers.
                              example: Madrid, Paris, Roma o Londres (en diferentes items)
                    createdAt:
                      type: string
                      format: date-time
                      description: Creation date and time of the game.
                      example: '2024-03-17T20:47:23.935Z'
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
                    example: User not found
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
                    example: Internal Server Error

  /history/games:
    get:
      summary: Get the history of all games.
      operationId: historyAllGames
      responses:
        '200':
          description: Information of games returned successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Game Id.
                      example: sqeweg12er56yg46u89k
                    username:
                      type: string
                      description: Username of the user.
                      example: student
                    points:
                      type: integer
                      description: The number of points that the user scored.
                      example: 1000
                    avgtime:
                      type: integer
                      description: The average time taken to answer questions in seconds.
                      example: 23
                    questions:
                      type: array
                      items:
                        type: object
                        properties:
                          question:
                            type: string
                            description: The question that was done.
                            example: ¿Cuál es la capital de España?
                          correctAnswer:
                            type: string
                            description: The correct answer for the question.
                            example: Madrid
                          answers:
                            type: array
                            items:
                              type: string
                              description: List with the possible answers.
                              example: Madrid, Paris, Roma o Londres (en diferentes items)
                    createdAt:
                      type: string
                      format: date-time
                      description: Creation date and time of the game.
                      example: '2024-03-17T20:47:23.935Z'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
                    example: Internal Server Error
                    
  /history/users:
    get:
      summary: Get the history of all users.
      operationId: historyAllUsers
      responses:
        '200':
          description: Information of users returned successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    username:
                      type: string
                      description: Username of the user.
                      example: student
                    tpoints:
                      type: integer
                      description: Total points earned by the user.
                      example: 1000
                    ttime:
                      type: integer
                      description: Total time spent by the user (in seconds).
                      example: 330
                    ngames:
                      type: integer
                      description: Number of games played by the user.
                      example: 2
                    createdAt:
                      type: string
                      format: date-time
                      description: Creation date and time of the user.
                      example: '2024-03-17T20:47:23.935Z'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
                    example: Internal Server Error