openapi: 3.0.0
info:
  title: GameService API
  description: Gateway OpenAPI specification.
  version: 0.2.0
servers:
  - url: http://localhost:8005
    description: Development server
  - url: http://gameservice:8005
    description: Production server
paths:

  /generateGame:
    get:
      summary: Generate the id for the game.
      operationId: generateGame
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Create the id of the game and returned successfuly.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The id of the game created.
                    example: Game id created (sqeweg12er56yg46u89k)
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
                    example: Internal Server Error

  /questions:
    get:
      summary: Generate questions for the game.
      operationId: questions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Game Id.
                  example: sqeweg12er56yg46u89k
      responses:
        '200':
          description: Question created and returned successfuly.
          content:
            application/json:
              schema:
                type: object
                properties:
                  answers:
                    type: List<String>
                    description: List with the possible answers.
                    example: Madrid, Paris, Roma o Londres.
                  question:
                    type: String
                    description: The question that is going to be done
                    example: ¿Capital de España?
                  correctAnswer:
                    type: String
                    description: The correct answer for the question      
                    example: Madrid.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
                    example: Internal Server Error
  /storeGame:
    post:
      summary: Stores the actual game in the database.
      operationId: storeGame
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Game Id.
                  example: sqeweg12er56yg46u89k
                username:
                  type: string
                  description: The name if the user.
                  example: username.
                points:
                  type: integer
                  description: The number of points that the user score.
                  example: 1000.
                questions:
                  answers:
                    type: List<String>
                    description: List with the possible answers.
                    example: Madrid, Paris, Roma o Londres.
                  question:
                    type: String
                    description: The question that is going to be done
                    example: ¿Capital de España?
                  correctAnswer:
                    type: String
                    description: The correct answer for the question
                    example: Madrid
                avgtime:
                  type: integer
                  description: The average time taken to answer questions in seconds.
                  example: 23
      responses:
        '200':
          description: Question created and returned successfuly.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The question that is going to be realized.
                    example: ¿Capital de España?
                  answers:
                    type: List<String>
                    description: List with the possible answers.
                    example: Madrid, Paris, Roma o Londres.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
                    example: Internal Server Error
